image: python:3.8-alpine

run_metadata_import:
  stage: deploy
  before_script:
    - apk add --no-cache bash # Ensure bash is available for date manipulation
  script:
    - pip install --cache-dir .pip_cache/ -r requirements.txt
    - mkdir -p logs
    - |
      echo "🕒 Start Time: $(date)"
    - START_TIME=$SECONDS
    - python3 ./main.py -l DEBUG
    - END_TIME=$SECONDS
    - DURATION=$((END_TIME-START_TIME))
    - ERRORS=$(grep -c 'error' logs/output.log) # Count warnings in output.log
    - echo "📊 **Execution Summary** 📊"
    - |
      echo -e "📊 **Execution Summary** 📊\n\
      🚀 Start Time: $(date -d @$START_TIME +"%Y-%m-%d %H:%M:%S")\n\
      🏁 End Time: $(date -d @$END_TIME +"%Y-%m-%d %H:%M:%S")\n\
      ⏱ Duration: $DURATION seconds\n\
      ❌ Number of Errors (Warnings): $ERRORS" | tee logs/summary.log
  artifacts:
    paths:
      - logs/
    expire_in: 4 weeks
  cache:
    paths:
      - .pip_cache/
    key: "${CI_COMMIT_REF_SLUG}"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
