image: python:3.8-alpine

stages:
  - main_task
  - summarize

run_metadata_import:
  stage: main_task
  before_script:
    - apk add --no-cache bash coreutils # Ensure bash and GNU coreutils are available
  script:
    - pip install --cache-dir .pip_cache/ -r requirements.txt
    - echo "Running main task and capturing logs"
    - START_TIME=$(date +%s)
    - python3 ./main.py -l DEBUG | tee main_task_logs.txt
    - ERRORS=$(grep -i "error" main_task_logs.txt | wc -l)
    - echo $ERRORS > error_count.txt
    - END_TIME=$(date +%s)
    - DURATION=$((END_TIME-START_TIME))
    - echo $START_TIME > start_time.txt
    - echo $END_TIME > end_time.txt
    - echo $DURATION > duration.txt
  artifacts:
    paths:
      - main_task_logs.txt
      - error_count.txt
      - start_time.txt
      - end_time.txt
      - duration.txt
    expire_in: 4 weeks
  cache:
    paths:
      - .pip_cache/
    key: "${CI_COMMIT_REF_SLUG}"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

summarize:
  stage: summarize
  script:
    - export ERRORS=$(cat error_count.txt)
    - export START_TIME=$(cat start_time.txt)
    - export END_TIME=$(cat end_time.txt)
    - export DURATION=$(cat duration.txt)
    - |
      "echo -e \"📊 **Execution Summary** 📊\n
      🚀 Start Time: $START_TIME\n
      🏁 End Time: $END_TIME\n
      ⏱ Duration: $DURATION seconds\n
      ❌ Number of Errors (Warnings): $ERRORS\""

  needs:
    - run_metadata_import
